spring:
  application:
    name: funding_project
  #DB connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: Yun422537265!
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #Swagger 3.0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #Redis
  data:
    redis:
#      host: redis
      host: localhost
      port: 6379

  security:
    user:
      name: user
      password: 1234

springdoc:
  api-docs:
    enabled: false
application:
  security:
    jwt:
      sensitive-key : {}
      private-key : {}
      access-expiration: 600000 # 10 mins
      refresh-expiration: 2067600000 # 24 days

server:
  port: 8081