spring:
  application:
    name: funding_project
  #DB connection
  datasource:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test_db
      username: root
      password: Yun422537265!


  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  sql:
    init:
      mode: always # h2같은 임베디드 데이터베이스 외 mysql같은 db에 data.sql로 초기화 하기 위함
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true # data.sql으로 스프링부트실행시 데이터삽입
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #Swagger 3.0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #Redis
  data:
    redis:
      #      host: redis
      host: localhost
      port: 6379


springdoc:
  api-docs:
    enabled: false
application:
  security:
    jwt:
      sensitive-key : awefawef
      secret-key: awef
      private-key : awef
      expiration: 6000000 # 100 mins

server:
  port: 8081